sudo: required
services:
  - docker

before_install:
  - docker build -t nikunjpatel1989/docker-react -f Dockerfile.dev .

script:
  - docker run nikunjpatel1989/docker-react npm run test -- --coverage